name: SmartSpawnerFilter
main: id.destaria.smartspawner.filter.SmartSpawnerFilterAddon
version: 1.0.0
api-version: 1.20
description: Adds permission enforcement around SmartSpawner placement and silk-touch drops.
softdepend:
  - SmartSpawner
authors:
  - X1Ds
commands:
  smartspawnerfilter:
    description: Reloads the SmartSpawner Filter configuration.
    usage: /<command> reload
    aliases:
      - ssf
permissions:
  sff.break:
    description: Base node; append .<world>.<entity> (e.g. sff.break.world.zombie) to allow per-mob breaks per world.
    default: op
  sff.place:
    description: Base node; append .<world>.<entity> (e.g. sff.place.world.creeper) to allow per-mob placement per world.
    default: op
  sff.natural:
    description: Grants access to the natural silk-touch SmartSpawner drop per world and mob type.
    default: op
  sff.stack:
    description: Allows stacking spawners in a world.
    default: op
  sff.reload:
    description: Allows reloading the addon configuration via command.
    default: op
