name: SmartSpawnerFilter
main: id.destaria.smartspawner.filter.SmartSpawnerFilterAddon
version: 1.0.0
api-version: 1.20
description: Adds permission enforcement around SmartSpawner placement and silk-touch drops.
softdepend:
  - SmartSpawner
authors:
  - X1Ds
permissions:
  sff.break:
    description: Base node; append .<entity> (e.g. sff.break.zombie) to allow per-mob breaks.
    default: op
  sff.place:
    description: Base node; append .<entity> (e.g. sff.place.creeper) to allow per-mob placement.
    default: op
  sff.natural:
    description: Grants access to the natural silk-touch SmartSpawner drop.
    default: op
